# Generated by Django 3.0.5 on 2020-05-01 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('vendor', models.CharField(max_length=64)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=512)),
                ('type', models.CharField(choices=[('L', 'laptop'), ('P', 'mobile phone'), ('M', 'monitor'), ('T', 'TV'), ('O', 'other')], max_length=1)),
                ('status', models.CharField(choices=[('R', 'ready for assignment'), ('A', 'assigned'), ('P', 'on repair'), ('T', 'retired'), ('L', 'lost'), ('S', 'stolen')], max_length=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=512)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Asset')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
